### ISSUE TITLE
 invalid alteration of the DEM

### ISSUE THREAD

**Issue by sebastianbeyer** [r-barnes/Barnes2013-FlatSurfaces#1]
Hi,
really nice work! I appreciate your algorithm and clear implementation.
On some DEMs I get a lot of this `invalid alteration of the DEM` warnings and I don't really understand what this means. On smaller test geometries this does not occur and by just looking at the coordinates at which it does I can not tell what is the problem. Maybe you could give me a hint, what you are checking with this?

**Comment by r-barnes** [comment]
Thank you!

I allude to this issue in Section 2.1 (p. 129) of the publication associated with this algorithm. The excerpt is:

> However, the precision of DEMs has increased considerably
> since G&M was designed and it is now possible to find DEMs
> which use the full width of single-precision floating-point storage
> units. In such a case, there is no negligible increment which can be
> added—every increment is a significant alteration of the DEM.
> In this case, incrementing a cell to resolve a flat may cause it to rise
> above surrounding cells which were formerly higher than it was,
> corrupting important information about the landscape. Ultimately,
> G&M provides no guarantees regarding its effect on a DEM.

I allude to it again in Section 2.5 (p. 131):

> Alternatively, if it is necessary to alter the DEM itself, as in G&M, the
> smallest possible increments should be used. In C and C++ this can be done
> using the N EXT A FTER function defined by the C99 and POSIX standards, which
> increases or decreases a floating-point number by the smallest possible
> increment in the direction of a second number; this is far preferable to an
> arbitrarily defined ε. Similar functions exist in other languages. It is also
> possible to check that this process does not cause problems: after a cell is
> incremented, the only neighboring cells which should be lower than it are
> those which were lower before it was incremented, unless the neighbors in
> question are part of the same flat.

The idea here is that your DEM may have a flat section which is very slightly depressed below the neighbouring terrain. Trying to enforce drainage on this section may imply a gradient such that, at the end opposite the outlet, the section now rises above terrain which should be above it.

As a concrete example, think of a parking lot surrounded by a curb with a single exit to the street: the curb raises the surrounding terrain only a few inches above the lot. Now, assume both that the lot is very large and that the minimal gradient you can impose on the lot to ensure drainage is a 5% gradient. If the lot is large enough, that 5% gradient will force you to raise parts of the lot above the surrounding curb.

For small DEMs this is unlikely to be an issue because, at least for floating point data, your gradient can be quite small. You will need a DEM with low relief and large flats for this problem to crop up.

The check you've found (which is on Line 573 of "flat_resolution.hpp") is supposed to notify you if this is occurring. Looking at it now, I am having difficulty convincing myself that it will do so correctly... though I think it could be made to do so with minor modifications.

Does this help explain things? If you feel like taking a look at the code, I'd be interested to know if you come to the same conclusion and resolution I do. I'll make a note to come back through and update things in a few days if you don't get around to it.

Best regards,
Richard

**Comment by r-barnes** [comment]
Just checking up to see if this helped!

**Comment by r-barnes** [comment]
I'm going to close this, but feel free to reopen if that didn't help.
